image: "ruby:2.7.1"

cache:
  paths:
    - vendor/ruby

rubocop:
  script:
    -  bundle exec rubocop


before_script:
  - ruby -v
  - bundler config set path 'vendor'
  - bundle install -j $(nproc)

rspec:
  script:
    - bundle exec rspec spec
