image: "ruby:2.7.1"

variables:
  TEST: "HELLO WORLD"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - bundle install -j $(nproc) --path vendor

rspec:
  script:
    - bundle exec rspec
